######################################################################
# Automatically generated by qmake (2.01a) wt. kwi 14 09:44:23 2009
######################################################################

! include(../../common.pri) {
	error( common.pri file does not exist!);
}

TEMPLATE = lib
TARGET = trivlog
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR += ../bin

target.path = $$INSTALL_ROOT/lib
INSTALLS += target

# Input
HEADERS += logger_t.h nullstream.h
SOURCES += logger_t.cpp
