#!/bin/sh

DIR=$1

if [ ! -d $DIR/bin ] ; then
	mkdir $DIR/bin
fi

cp src/bin/fivermain $DIR/bin/fivermain
cp QConsole/Console/*.so* $DIR/bin/
cp QConsole/QConsole/*.so* $DIR/bin/
cp src/bin/*.so* $DIR/bin/

echo "#!/bin/sh" > $DIR/start
echo "export FIVERDIR=$DIR" >> $DIR/start
echo "export LD_LIBRARY_PATH=$DIR/bin" >> $DIR/start
echo "$DIR/bin/fivermain \$1 \$2 \$3" >> $DIR/start
chmod a+x $DIR/start

