#!/bin/sh

export FIVERDIR=`pwd`
export FIVER_XML_FIELD_CONFIG=$FIVERDIR/src/config.txt

export LD_LIBRARY_PATH=$FIVERDIR/src/boxmgr:$FIVERDIR/src/attr:$FIVERDIR/src/coremesh2/lib:$FIVERDIR/src/meshreader2/lib:$FIVERDIR/QConsole/QConsole:$FIVERDIR/QConsole/Console:$FIVERDIR/src/bin
$FIVERDIR/src/bin/fivermain # -d $1 $2 $3 $4 $5 $6 $7 $8 $9 $10

#export FIVERDIR=.

#export LD_LIBRARY_PATH=$FIVERDIR/src/boxmgr:$FIVERDIR/src/attr:$FIVERDIR/src/coremesh2/lib:$FIVERDIR/src/meshreader2/lib:$FIVERDIR/QConsole/QConsole:$FIVERDIR/QConsole/Console:$FIVERDIR/src/bin
#$FIVERDIR/src/bin/fivermain # -d $1 $2 $3 $4 $5 $6 $7 $8 $9 $10
