#############################################################################
# Makefile for building: fivermain
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?r. sty 25 10:24:49 2012
# Project:  fiver2.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile fiver2.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src-log \
		sub-src-boxmgr \
		sub-src-attr \
		sub-src-coremesh2 \
		sub-src-meshreader2 \
		sub-src \
		sub-src-meshjoiner

src/log//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/log/ || $(MKDIR) src/log/ 
	cd src/log/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/log/log.pro -o $(MAKEFILE)
sub-src-log-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/log/ || $(MKDIR) src/log/ 
	cd src/log/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/log/log.pro -o $(MAKEFILE)
sub-src-log: src/log//$(MAKEFILE) FORCE
	cd src/log/ && $(MAKE) -f $(MAKEFILE)
sub-src-log-make_default: src/log//$(MAKEFILE) FORCE
	cd src/log/ && $(MAKE) -f $(MAKEFILE) 
sub-src-log-make_first: src/log//$(MAKEFILE) FORCE
	cd src/log/ && $(MAKE) -f $(MAKEFILE) first
sub-src-log-all: src/log//$(MAKEFILE) FORCE
	cd src/log/ && $(MAKE) -f $(MAKEFILE) all
sub-src-log-clean: src/log//$(MAKEFILE) FORCE
	cd src/log/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-log-distclean: src/log//$(MAKEFILE) FORCE
	cd src/log/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-log-install_subtargets: src/log//$(MAKEFILE) FORCE
	cd src/log/ && $(MAKE) -f $(MAKEFILE) install
sub-src-log-uninstall_subtargets: src/log//$(MAKEFILE) FORCE
	cd src/log/ && $(MAKE) -f $(MAKEFILE) uninstall
src/boxmgr//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/boxmgr/ || $(MKDIR) src/boxmgr/ 
	cd src/boxmgr/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/boxmgr/boxmgr.pro -o $(MAKEFILE)
sub-src-boxmgr-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/boxmgr/ || $(MKDIR) src/boxmgr/ 
	cd src/boxmgr/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/boxmgr/boxmgr.pro -o $(MAKEFILE)
sub-src-boxmgr: src/boxmgr//$(MAKEFILE) FORCE
	cd src/boxmgr/ && $(MAKE) -f $(MAKEFILE)
sub-src-boxmgr-make_default: src/boxmgr//$(MAKEFILE) FORCE
	cd src/boxmgr/ && $(MAKE) -f $(MAKEFILE) 
sub-src-boxmgr-make_first: src/boxmgr//$(MAKEFILE) FORCE
	cd src/boxmgr/ && $(MAKE) -f $(MAKEFILE) first
sub-src-boxmgr-all: src/boxmgr//$(MAKEFILE) FORCE
	cd src/boxmgr/ && $(MAKE) -f $(MAKEFILE) all
sub-src-boxmgr-clean: src/boxmgr//$(MAKEFILE) FORCE
	cd src/boxmgr/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-boxmgr-distclean: src/boxmgr//$(MAKEFILE) FORCE
	cd src/boxmgr/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-boxmgr-install_subtargets: src/boxmgr//$(MAKEFILE) FORCE
	cd src/boxmgr/ && $(MAKE) -f $(MAKEFILE) install
sub-src-boxmgr-uninstall_subtargets: src/boxmgr//$(MAKEFILE) FORCE
	cd src/boxmgr/ && $(MAKE) -f $(MAKEFILE) uninstall
src/attr//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/attr/ || $(MKDIR) src/attr/ 
	cd src/attr/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/attr/attr.pro -o $(MAKEFILE)
sub-src-attr-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/attr/ || $(MKDIR) src/attr/ 
	cd src/attr/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/attr/attr.pro -o $(MAKEFILE)
sub-src-attr: src/attr//$(MAKEFILE) FORCE
	cd src/attr/ && $(MAKE) -f $(MAKEFILE)
sub-src-attr-make_default: src/attr//$(MAKEFILE) FORCE
	cd src/attr/ && $(MAKE) -f $(MAKEFILE) 
sub-src-attr-make_first: src/attr//$(MAKEFILE) FORCE
	cd src/attr/ && $(MAKE) -f $(MAKEFILE) first
sub-src-attr-all: src/attr//$(MAKEFILE) FORCE
	cd src/attr/ && $(MAKE) -f $(MAKEFILE) all
sub-src-attr-clean: src/attr//$(MAKEFILE) FORCE
	cd src/attr/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-attr-distclean: src/attr//$(MAKEFILE) FORCE
	cd src/attr/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-attr-install_subtargets: src/attr//$(MAKEFILE) FORCE
	cd src/attr/ && $(MAKE) -f $(MAKEFILE) install
sub-src-attr-uninstall_subtargets: src/attr//$(MAKEFILE) FORCE
	cd src/attr/ && $(MAKE) -f $(MAKEFILE) uninstall
src/coremesh2//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/coremesh2/ || $(MKDIR) src/coremesh2/ 
	cd src/coremesh2/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/coremesh2/coremesh2.pro -o $(MAKEFILE)
sub-src-coremesh2-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/coremesh2/ || $(MKDIR) src/coremesh2/ 
	cd src/coremesh2/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/coremesh2/coremesh2.pro -o $(MAKEFILE)
sub-src-coremesh2: src/coremesh2//$(MAKEFILE) FORCE
	cd src/coremesh2/ && $(MAKE) -f $(MAKEFILE)
sub-src-coremesh2-make_default: src/coremesh2//$(MAKEFILE) FORCE
	cd src/coremesh2/ && $(MAKE) -f $(MAKEFILE) 
sub-src-coremesh2-make_first: src/coremesh2//$(MAKEFILE) FORCE
	cd src/coremesh2/ && $(MAKE) -f $(MAKEFILE) first
sub-src-coremesh2-all: src/coremesh2//$(MAKEFILE) FORCE
	cd src/coremesh2/ && $(MAKE) -f $(MAKEFILE) all
sub-src-coremesh2-clean: src/coremesh2//$(MAKEFILE) FORCE
	cd src/coremesh2/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-coremesh2-distclean: src/coremesh2//$(MAKEFILE) FORCE
	cd src/coremesh2/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-coremesh2-install_subtargets: src/coremesh2//$(MAKEFILE) FORCE
	cd src/coremesh2/ && $(MAKE) -f $(MAKEFILE) install
sub-src-coremesh2-uninstall_subtargets: src/coremesh2//$(MAKEFILE) FORCE
	cd src/coremesh2/ && $(MAKE) -f $(MAKEFILE) uninstall
src/meshreader2//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/meshreader2/ || $(MKDIR) src/meshreader2/ 
	cd src/meshreader2/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/meshreader2/meshreader2.pro -o $(MAKEFILE)
sub-src-meshreader2-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/meshreader2/ || $(MKDIR) src/meshreader2/ 
	cd src/meshreader2/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/meshreader2/meshreader2.pro -o $(MAKEFILE)
sub-src-meshreader2: src/meshreader2//$(MAKEFILE) FORCE
	cd src/meshreader2/ && $(MAKE) -f $(MAKEFILE)
sub-src-meshreader2-make_default: src/meshreader2//$(MAKEFILE) FORCE
	cd src/meshreader2/ && $(MAKE) -f $(MAKEFILE) 
sub-src-meshreader2-make_first: src/meshreader2//$(MAKEFILE) FORCE
	cd src/meshreader2/ && $(MAKE) -f $(MAKEFILE) first
sub-src-meshreader2-all: src/meshreader2//$(MAKEFILE) FORCE
	cd src/meshreader2/ && $(MAKE) -f $(MAKEFILE) all
sub-src-meshreader2-clean: src/meshreader2//$(MAKEFILE) FORCE
	cd src/meshreader2/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-meshreader2-distclean: src/meshreader2//$(MAKEFILE) FORCE
	cd src/meshreader2/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-meshreader2-install_subtargets: src/meshreader2//$(MAKEFILE) FORCE
	cd src/meshreader2/ && $(MAKE) -f $(MAKEFILE) install
sub-src-meshreader2-uninstall_subtargets: src/meshreader2//$(MAKEFILE) FORCE
	cd src/meshreader2/ && $(MAKE) -f $(MAKEFILE) uninstall
src//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/src.pro -o $(MAKEFILE)
sub-src: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
src/meshjoiner//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/meshjoiner/ || $(MKDIR) src/meshjoiner/ 
	cd src/meshjoiner/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/meshjoiner/meshjoiner.pro -o $(MAKEFILE)
sub-src-meshjoiner-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/meshjoiner/ || $(MKDIR) src/meshjoiner/ 
	cd src/meshjoiner/ && $(QMAKE) /home/szmurlor/fiver/trunk/src/meshjoiner/meshjoiner.pro -o $(MAKEFILE)
sub-src-meshjoiner: src/meshjoiner//$(MAKEFILE) FORCE
	cd src/meshjoiner/ && $(MAKE) -f $(MAKEFILE)
sub-src-meshjoiner-make_default: src/meshjoiner//$(MAKEFILE) FORCE
	cd src/meshjoiner/ && $(MAKE) -f $(MAKEFILE) 
sub-src-meshjoiner-make_first: src/meshjoiner//$(MAKEFILE) FORCE
	cd src/meshjoiner/ && $(MAKE) -f $(MAKEFILE) first
sub-src-meshjoiner-all: src/meshjoiner//$(MAKEFILE) FORCE
	cd src/meshjoiner/ && $(MAKE) -f $(MAKEFILE) all
sub-src-meshjoiner-clean: src/meshjoiner//$(MAKEFILE) FORCE
	cd src/meshjoiner/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-meshjoiner-distclean: src/meshjoiner//$(MAKEFILE) FORCE
	cd src/meshjoiner/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-meshjoiner-install_subtargets: src/meshjoiner//$(MAKEFILE) FORCE
	cd src/meshjoiner/ && $(MAKE) -f $(MAKEFILE) install
sub-src-meshjoiner-uninstall_subtargets: src/meshjoiner//$(MAKEFILE) FORCE
	cd src/meshjoiner/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: fiver2.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile fiver2.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile fiver2.pro

qmake_all: sub-src-log-qmake_all sub-src-boxmgr-qmake_all sub-src-attr-qmake_all sub-src-coremesh2-qmake_all sub-src-meshreader2-qmake_all sub-src-qmake_all sub-src-meshjoiner-qmake_all FORCE

make_default: sub-src-log-make_default sub-src-boxmgr-make_default sub-src-attr-make_default sub-src-coremesh2-make_default sub-src-meshreader2-make_default sub-src-make_default sub-src-meshjoiner-make_default FORCE
make_first: sub-src-log-make_first sub-src-boxmgr-make_first sub-src-attr-make_first sub-src-coremesh2-make_first sub-src-meshreader2-make_first sub-src-make_first sub-src-meshjoiner-make_first FORCE
all: sub-src-log-all sub-src-boxmgr-all sub-src-attr-all sub-src-coremesh2-all sub-src-meshreader2-all sub-src-all sub-src-meshjoiner-all FORCE
clean: sub-src-log-clean sub-src-boxmgr-clean sub-src-attr-clean sub-src-coremesh2-clean sub-src-meshreader2-clean sub-src-clean sub-src-meshjoiner-clean FORCE
distclean: sub-src-log-distclean sub-src-boxmgr-distclean sub-src-attr-distclean sub-src-coremesh2-distclean sub-src-meshreader2-distclean sub-src-distclean sub-src-meshjoiner-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-log-install_subtargets sub-src-boxmgr-install_subtargets sub-src-attr-install_subtargets sub-src-coremesh2-install_subtargets sub-src-meshreader2-install_subtargets sub-src-install_subtargets sub-src-meshjoiner-install_subtargets FORCE
uninstall_subtargets: sub-src-log-uninstall_subtargets sub-src-boxmgr-uninstall_subtargets sub-src-attr-uninstall_subtargets sub-src-coremesh2-uninstall_subtargets sub-src-meshreader2-uninstall_subtargets sub-src-uninstall_subtargets sub-src-meshjoiner-uninstall_subtargets FORCE

sub-src-log-check: src/log/$(MAKEFILE)
	cd src/log/ && $(MAKE) check
sub-src-boxmgr-check: src/boxmgr/$(MAKEFILE)
	cd src/boxmgr/ && $(MAKE) check
sub-src-attr-check: src/attr/$(MAKEFILE)
	cd src/attr/ && $(MAKE) check
sub-src-coremesh2-check: src/coremesh2/$(MAKEFILE)
	cd src/coremesh2/ && $(MAKE) check
sub-src-meshreader2-check: src/meshreader2/$(MAKEFILE)
	cd src/meshreader2/ && $(MAKE) check
sub-src-check: src/$(MAKEFILE)
	cd src/ && $(MAKE) check
sub-src-meshjoiner-check: src/meshjoiner/$(MAKEFILE)
	cd src/meshjoiner/ && $(MAKE) check
check: sub-src-log-check sub-src-boxmgr-check sub-src-attr-check sub-src-coremesh2-check sub-src-meshreader2-check sub-src-check sub-src-meshjoiner-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

