#!/bin/sh

export FIVERDIR=.

export LD_LIBRARY_PATH=$FIVERDIR/libQGLViewer-2.2.6-1/QGLViewer:$FIVERDIR/src/boxmgr:$FIVERDIR/src/attr:$FIVERDIR/src/coremesh2/lib:$FIVERDIR/src/meshreader2/lib:$FIVERDIR/qwt-5.1.1/lib:$FIVERDIR/QConsole/QConsole:$FIVERDIR/QConsole/Console:$FIVERDIR/src/bin
$FIVERDIR/src/bin/fivermain # -d $1 $2 $3 $4 $5 $6 $7 $8 $9 $10
