######################################################################
# Automatically generated by qmake (2.01a) wt. kwi 14 09:44:23 2009
######################################################################

TEMPLATE = lib
TARGET = trivlog
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR += ../bin

# Input
HEADERS += logger_t.h nullstream.h
SOURCES += logger_t.cpp
