######################################################################
# Automatically generated by qmake (1.07a) Mon Dec 19 19:57:39 2005
######################################################################

TEMPLATE = lib
INCLUDEPATH += .
DESTDIR = ../bin

target.path = /usr/local/lib
INSTALLS += target

# Input
HEADERS += boxbox.h boxcon.h boxmgr.h boxobj.h
SOURCES += boxbox.cpp boxcon.cpp boxmgr.cpp boxobj.cpp




